### ISSUE TITLE
add-apt-repository can't add repositories with [arch=amd64] - mintsource/tricia-1.9.1

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintsources#188]
Hi,

Mintsource's add-apt-repository can't add repositories with [arch=amd64] .

You can try following command for reproducing issue.

`sudo add-apt-repository 'deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian bionic contrib'
`

I tried with mintsource/tricia-1.9.1, I didn't try previous versions

**Comment by xenopeek** [comment]
I tried adding the repository without [arch=amd64], as the [Debian wiki](https://wiki.debian.org/VirtualBox#Debian_9_.22Stretch.22) has the command:

`sudo add-apt-repository 'deb http://download.virtualbox.org/virtualbox/debian bionic contrib'`

But then updating results in this notice:

> N: Skipping acquire of configured file 'contrib/binary-i386/Packages' as repository 'http://download.virtualbox.org/virtualbox/debian bionic InRelease' doesn't support architecture 'i386'

So it's there for a reason. Currently the add_repository_via_cli function in [mintSources.py](https://github.com/linuxmint/mintsources/blob/master/usr/lib/linuxmint/mintSources/mintSources.py) does not have support for [arch=X] string on the repository line so that would need to be added.
