### ISSUE TITLE
Feature request: when downgrading packages, show the origin of the installed version

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintsources#189]
The useful Downgrader does not show me where my version of a package came from. Screenshot:

![image](https://user-images.githubusercontent.com/47056543/71316272-e2493700-2464-11ea-9568-22bdcb5a169e.png)

So, if I wish to downgrade some packages from some single particular source - a source I've seen in Synaptic - then it is not easy to use your tool to do it. I didn't think I could have Synaptic open at the same time as your tool (because of an apt conflict). It turns out I can, but I imagine a conflict might occur - when apt actually gets invoked. Here's a screenshot of Synaptic: 

![image](https://user-images.githubusercontent.com/47056543/71316302-63a0c980-2465-11ea-8e57-e25b28810462.png)

Now, one can use Synaptic to do the downgrade itself - but not very easily.

If your Downgrader (sorry: I don't know its internal name) could be made to show the source of installed packages, then that would be useful.

**Comment by xenopeek** [comment]
This is a misunderstanding about what downgrade foreign packages in mintsources does. It's not general package downgrade as Synaptic offers—it is for downgrading packages that you installed or upgraded from a repository you previously had configured but have since removed and no other configured repository has the same package version. 

So long as you have the repository configured on your system it's not a foreign package so mintsources won't offer to downgrade it and Synaptic will show its origin (because the repository is configured). After you remove the repository it becomes a foreign package (Synaptic calls the status 'local') so mintsources offers to downgrade it and Synaptic will no longer show its origin (as you've removed the repository it can no longer do so).

**Comment by LinuxOnTheDesktop** [comment]
@xenopeek Thank you for enlightening me. Still, I think that many people are likely to have this misunderstanding. If so, then action on your side seems needed.
