### ISSUE TITLE
Check existence of /generated/path/mintsources.conf

### ISSUE THREAD

**Issue by VolMi** [linuxmint/mintsources#36]
Say you replaced /etc/lsb-release with ubuntu's version from the package `base-files`, so `lsb_release -sc` returns ubuntu's codename.
Then `apt-add-repository` wants to access  `/usr/share/mintsources/zealouszackaloo/mintsources.conf` which [results in](https://github.com/linuxmint/mintsources/blob/master/usr/lib/linuxmint/mintSources/mintSources.py#L1263):

```
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1263, in <module>
    codename = config_parser.get("general", "base_codename
  File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'general'
```

There should be at least a check if the file exists, first. And a more helpful error message, probably.

**Comment by ack0329** [comment]
is there a solution here - so many of us have this problem with mint

**Comment by mrbarletta** [comment]
Had the same problem with netrunner 14 - Did :
````
sudo apt-get remove mintsources
````
worked fine after that

**Comment by thakkarparth007** [comment]
I think the error is happening not because the file doesn't exist - I think it does. But the code is not able to access the file. If you look at mintSources.py, 

```python
            lsb_codename = commands.getoutput("lsb_release -sc")
            config_parser = ConfigParser.RawConfigParser()
            config_parser.read("/usr/share/mintsources/%s/mintsources.conf" % lsb_codename)
            codename = config_parser.get("general", "base_codename")
```

This line shows that the file is being accessed using the lsb_release command. If the command doesn't exist, then the lsb_codename variable doesn't contain the right value, because of which the conf file doesn't get loaded correctly.

Not sure if this is the reason for this error with everyone, but at least in the case of my friend, the lsb_release command didn't exist. On installing it on her system, this problem was gone - the conf file _did_ exist, it just couldn't be accessed.

**Comment by ooker777** [comment]
`remove mintsources` doesn't fix the error for me. Using `lsb_release -rd; lsb_release -sc` as suggested in this [Mint forum](https://forums.linuxmint.com/viewtopic.php?t=180552) give me two duplicated errors:

    Traceback (most recent call last):
      File "/usr/bin/lsb_release", line 101, in <module>
        main()
      File "/usr/bin/lsb_release", line 65, in main
        distinfo = lsb_release.get_distro_information(options.upstream)
      File "/usr/lib/python3/dist-packages/lsb_release.py", line 374, in get_distro_information
        lsbinfo = get_lsb_information(upstream)
      File "/usr/lib/python3/dist-packages/lsb_release.py", line 354, in get_lsb_information
        for line in lsb_release_file:
      File "/usr/lib/python3.4/codecs.py", line 313, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 1: invalid continuation byte
