### ISSUE TITLE
Aborting the "Remove Foreign Packages" process gives a root shell

### ISSUE THREAD

**Issue by Nihlus** [linuxmint/mintsources#71]
Running "Remove Foreign Packages" from Software Sources can produce a live root terminal if the user responds with "n" instead of "Y" at the confirmation prompt. While this is still behind one password, an unattended run of this program may cause a severe local security breach.

This is not an intermittent bug, and will always happen if the following steps are followed.

Steps to reproduce:
1. Open "Software Sources".
2. Navigate to "Maintenance".'
3. Press "Remove foreign packages".
4. Select at least one package.
5. Press "Remove".
6. At the apt prompt, answer "n".
7. The command output window will now drop to an active root shell.

System information:
Linux Mint 17.3 "Rosa" Cinnamon Edition (64-bit)
mintsources v1.5.2
![rootshell](https://cloud.githubusercontent.com/assets/2340428/13046605/04122e44-d3da-11e5-98bc-2cd4b9fde2c0.png)

**Comment by clefebvre** [comment]
Good point. The same could be said about an unattended root nemo instance, or an unattended root terminal instance.

Considering the importance of user data (private keys, browser passwords etc..) the same could be said about non-root apps running in user mode. The issue is present the minute the computer is left unattended really.
