### ISSUE TITLE
Use pkexec instead of if-else with gksu

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mintsources#75]
pkexec is distro-agnostic and standard (freedesktop.org), I guess it would be better to switch all mint sudo-software to pkexec. What do you think?
In current project: https://github.com/linuxmint/mintsources/blob/master/usr/bin/software-sources

**Comment by dg1727** [comment]
I'm about to submit some pull requests which are meant to implement this.  

The advantage of `pkexec` over `gksu` (at least versions of `gksu` that I've used) is that `pkexec` allows **any** admin user to select their name from a list, then enter their password.  `gksu` only allows the logged-in user to do this.  `pkexec` is much more convenient when I'm helping a user - while that user stays logged in, I can authorize admin operations without the user having to type her/his password.  

Accordingly, I have set `<allow_active>` in all of the .policy files to `auth_admin_keep`.  (See the `polkit` manpage.)  

For consistency, I have set all `<allow_any>` and `<allow_inactive>` to `no`.  Setting these values to anything else doesn't make a lot of sense to me in most scenarios.  

I didn't use `.pkexec` in the filenames:  
- Out of a couple of dozen pre-existing `.policy` files in the distro I'm using (LMDE 2 beta), the only ones whose names include `.pkexec` are 2 from Ubuntu and one of the two from Debian.  
- I made an exception in leaving "org.nemo.root.policy" named as-is, because calling the action just "org.nemo" (filename `org.nemo.policy`) assumes that Nemo will never have any other kind of action (maybe formatting removable media or something) that requires `pkexec`.  

It's my impression that the filename and the action ID aren't used by `pkexec`, which seems to scan the file contents for the executable name.  (The action ID is shown in the password dialog, but software doesn't place any requirements on the action ID AFAICT.)  
- Therefore, we can set the filename & action ID to whatever we want -- 
- **except** if the .policy file is for a D-Bus service, in which case the action ID apparently needs to match the D-Bus service name.  (This isn't well documented on the Web - https://techbase.kde.org/Development/Tutorials/PolicyKit/Introduction says it is a "convenience", but I'm guessing it is mandatory.)  That case seems to apply to org.cinnamon.settingsdaemon.datetimemechanism.policy, so I didn't rename it to org.cinnamon.settings-daemon.datetime.policy (notice the hyphen), which I would have liked to do for consistency with the other 2 `cinnamon-settings-daemon` .policy files.  And since I prefer the hyphen, I didn't remove it from the other 2 filenames.  :)
- It is nice to the (savvy) user to have the filename be equal to the action ID plus `.policy` so the user can easily tell which .policy file contains that action ID, if the user wants to troubleshoot.  I followed this convention.  

I tried to keep formatting consistent across the files, including making some minor changes that weren't strictly needed (sorting directory names in some auxiliary files).  

I changed references to "Authentication" to language like "Please enter your password" because the existing Linux Mint text that I found used the latter wording.  

I changed `org.linuxmint` (in filenames & action IDs) to `com.linuxmint` because the website is `linuxmint.com` rather than `linuxmint.org`.  This is only aesthetic, because the .policy files have a separate field for URL.  

For L10n, I added (to some of the projects) files `polkit.its` and `polkit.loc` from https://cgit.freedesktop.org/polkit/commit/?id=c78819245ff8a270f97c9f800773e727918be838
According to that Git browser, these 2 files are going to be included in version 0.114 of PolKit.  I found these 2 files by reading https://blogs.gnome.org/mclasen/2016/07/21/using-modern-gettext/  
I changed the `locatingRules/locatingRule/name` attribute in the polkit.loc file from `"polkit policy"` to `"PolkitPolicy"` to avoid having to quote the space on the command line (`-L` or `--language=` option to `xgettext`).

**Comment by dg1727** [comment]
I am going to modify my Cinnamon pull request, as well as not-yet-submitted pull request against project "mdm", based on comment about use of `mint-which-launcher.py`.

**Comment by SamBurgos** [comment]
Great job on this and I agree with the idea, now that I remember the option of "Remove applications" available on Cinnamon itself (at least on Mint) depends on gksu and it will be great for it to use pkexec as well, I am not sure if I will be able to help but I leave a link to an article related to it

[http://www.rapgenic.it/wp/tweaking-cinnamon-in-arch-linux/](http://www.rapgenic.it/wp/tweaking-cinnamon-in-arch-linux/)

**Comment by dg1727** [comment]
**SamBurgos,** thank you for pointing that out (and for the link to the article).  Pull request https://github.com/linuxmint/Cinnamon/pull/6336 is meant to address that.

**Comment by AsciiWolf** [comment]
Any news regarding this issue and related PRs? Will they get merged?

**Comment by salphaon** [comment]
@AsciiWolf See #89

**Comment by xenopeek** [comment]
pkexec was enabled mid last year for mintsources.
